<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-01-03T14:38:30-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Bad Mood',
    'locale' => 'en_US',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1451849770,
        'latest_version' => '5.7.5.3',
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
);
